cfg = db.jobConfig(...
    'path', 'D:\OneDrive - Baylor College of Medicine\Paper_201906_GEVI\Fstim\20201008 double blind\Benchmarking repeat\2pFstim data', ...
    'tgtCh\path', 'video', ...
    'tgtCh\f', 0, ...
    'refCh\path', 'image', ...
    'refCh\f', 0, ...
    'refCh\ch', 2, ...
    'noiseLevel', 50, ...
    'selectRatio', [0.05, 0.5],...
    'stim', '2p stim 1811Eric-20181115-221006.ams4100');

i = 3;
figure(),
subplot(5,1,1),imshow(T_fov.RMap{i},[0,100]);
subplot(5,1,2),imshow(T_fov.fgMask{i},[]);
subplot(5,1,3),imshow(T_fov.finalMask{i},[]);
subplot(5,1,4),plot(T_fov.template{i});
subplot(5,1,5),T_fov.TraceFinal{i});

T_well  = innerjoin(T_well, T_group, 'Keys','Group',...
    'RightVariables','Name');

%%
cfg = db.jobConfig(...
    'path', 'D:\OneDrive - Baylor College of Medicine\Paper_201906_GEVI\Fstim\20201008 double blind\Benchmarking repeat\1pFstim data', ...
    'tgtCh\path', 'video', ...
    'tgtCh\f', 0, ...
    'tgtCh\noise', 0, ... 
    'refCh\path', 'image', ...
    'refCh\f', 0, ...
    'refCh\ch', 1, ...
    'refCh\noise', 20, ...
    'selectRatio', [0.2, 0.8],...
    'tcorrFilt', '1000:6800', ... % time/frames for correlation filt
    'stim', 'sync 1pstim comp-20201008-150543.ams4100');